project_name: arct
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    id: "arct"
    dir: .
    main: ./cmd/arc
dockers:
- image_templates: ["ghcr.io/RustedPipe/arct:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/RustedPipe/arct
  - --label=org.opencontainers.image.source=https://github.com/RustedPipe/arct
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
nfpms:
- maintainer: Lisa Brown <lbrown@rustedpipe.xyz>
  description: Arct log processing utility.
  homepage: https://github.com/RustedPipe/arct
  license: MIT
  formats:
  - deb
  - rpm

