project_name: arct
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    id: "arct"
    dir: .
    main: ./cmd/arc
#dockers:
#- image_templates: ["ghcr.io/RustedPipe/arct:{{ .Version }}"]
#  dockerfile: Dockerfile
nfpms:
- maintainer: Lisa Brown <lbrown@rustedpipe.xyz>
  description: Arct log processing utility.
  homepage: https://github.com/RustedPipe/arct
  license: MIT
  formats:
  - deb
  - rpm

